#!/bin/bash
##############################################################################
# Configure the hibernate XML mapping files.
# 
# Author: Oren E. Livne
# Date: 05-AUG-07
##############################################################################

if [ $# -gt 1 ]; then
    echo "Usage: linecount [configuration]"
    exit 1
fi

# Useful aliases
COMMON=config/common
HEADER=$COMMON/hibernate.cfg.header
FOOTER=$COMMON/hibernate.cfg.footer

#----------------------------------------------------------------------------------------
# Generate Hibernate XML configuration files from .config files in each config directory
#----------------------------------------------------------------------------------------
for d in $( ls -1 config | egrep -v ".svn" | egrep -v "_svn" | egrep -v "*.txt" )
do
	dir=config/$d
	for line in $( find $dir -name "*.config" | sed 's~'$dir/'~~g' | sed 's/.config//g' );
	do
	    cat $HEADER $dir/$line.config $COMMON/$line.mapping $FOOTER > $dir/$line.cfg.xml
	done
done

#----------------------------------------------------------------------------------------
# Generate the default Hibernate XML mapping files under src using
# the header files in config/common
#----------------------------------------------------------------------------------------
dir=$COMMON
for line in $( find $dir -name "*.config" | sed 's~'$dir/'~~g' | sed 's/.config//g' );
do
    cat $HEADER $dir/$line.config $COMMON/$line.mapping $FOOTER > src/$line.cfg.xml
done

#----------------------------------------------------------------------------------------
# If an argument is supplied, generate the default Hibernate XML files under src using
# the header file in the specified configuration dir, possibly overriding some common
# configuration files.
#----------------------------------------------------------------------------------------

if [ $# -gt 0 ]; then
	dir=config/$1
	for line in $( find $dir -name "*.config" | sed 's~'$dir/'~~g' | sed 's/.config//g' );
	do
	    cp $dir/$line.cfg.xml src
	done
fi
