/*****************************************************************************************
 * Source File: AbstractTreeMatcher.java
 ****************************************************************************************/
package net.ruready.parser.tree.exports;

import net.ruready.common.parser.core.entity.Match;
import net.ruready.common.parser.core.manager.AbstractCompiler;
import net.ruready.common.parser.core.manager.AbstractMatcher;
import net.ruready.common.parser.core.manager.Parser;
import net.ruready.common.parser.core.tokens.Tokenizer;
import net.ruready.common.tree.AbstractListTreeNode;
import net.ruready.parser.options.exports.ParserOptions;
import net.ruready.parser.service.exception.MathParserException;
import net.ruready.parser.tokenizer.entity.MathAssembly;
import net.ruready.parser.tokenizer.manager.MathTokenizer;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * This runs a compiler and a matcher to parse an input String into a tree.
 * <p>
 * -------------------------------------------------------------------------<br>
 * (c) 2006-2007 Continuing Education, University of Utah<br>
 * All copyrights reserved. U.S. Patent Pending DOCKET NO. 00846 25702.PROV
 * <p>
 * This file is part of the RUReady Program software.<br>
 * Contact: Nava L. Livne <code>&lt;nlivne@aoce.utah.edu&gt;</code><br>
 * Academic Outreach and Continuing Education (AOCE)<br>
 * 1901 East South Campus Dr., Room 2197-E<br>
 * University of Utah, Salt Lake City, UT 84112-9359<br>
 * U.S.A.<br>
 * Day Phone: 1-801-587-5835, Fax: 1-801-585-5414<br>
 * <br>
 * Please contact these numbers immediately if you receive this file without permission
 * from the authors. Thank you.<br>
 * -------------------------------------------------------------------------
 * 
 * @author Oren E. Livne <code>&lt;olivne@aoce.utah.edu&gt;</code>
 * @version Sep 8, 2007
 */
public abstract class AbstractTreeMatcher<T extends AbstractListTreeNode<?, ?>>
		implements AbstractMatcher
{
	// ========================= CONSTANTS =================================

	/**
	 * A logger that helps identify this class' printouts.
	 */
	@SuppressWarnings("unused")
	private static final Log logger = LogFactory.getLog(AbstractTreeMatcher.class);

	// ========================= FIELDS ====================================

	// -------------------------------------------------
	// Required input
	// -------------------------------------------------
	// Parser control options
	private final ParserOptions options;

	// -------------------------------------------------
	// Convenient local variables
	// -------------------------------------------------

	// the parser generated by the compiler
	private Parser parser;

	// -------------------------------------------------
	// Output input
	// -------------------------------------------------
	// target object
	private T target;

	// Matching statistics
	private boolean completeMatch;

	// ========================= CONSTRUCTORS ==============================

	/**
	 * Initialize a tree string matcher from options.
	 * 
	 * @param options
	 *            control options object
	 * @param compiler
	 *            Compiler to prepare the parser used by the matcher
	 */
	public AbstractTreeMatcher(final ParserOptions options,
			final AbstractCompiler compiler)
	{
		super();
		this.options = options;
		this.parser = compiler.parser();
	}

	// ========================= ABSTRACT METHODS ==========================

	/**
	 * Create a tree of this type with a single root node that holds <code>null</code>
	 * data. This serves as the initial target.
	 * 
	 * @return a tree of this type with a single root node that holds <code>null</code>
	 *         data
	 */
	protected abstract T createEmptyTree();

	// ========================= METHODS ===================================

	/**
	 * Parse (match) an expression from in a string. The resulting variable values are
	 * inside the returned target object.
	 * 
	 * @param s
	 *            the string to parse.
	 * @throws MathParserException
	 *             if this parser does not recognize the given string as a valid
	 *             expression.
	 */
	@SuppressWarnings("unchecked")
	public final void match(String s)
	{
		// Initialize and customize the tokenizer
		Tokenizer t =
				new MathTokenizer(options.getVariableNames(), options.getArithmeticMode());
		// Tokenizer t = new TreeTokenizer(new TreeSymbolState());
		t.setString(s);
		MathAssembly in = new MathAssembly(t);

		// ---------------------------------------------------------------
		// Note: The assemblers plugged into the matching process will build
		// a syntax tree (class of type SyntaxTreeNode). After it is built,
		// we insert it into an SyntaxTreeNode object with a copy of the
		// list of tokens in the parsed string.
		// ---------------------------------------------------------------

		// Initialize the target to be an empty tree
		in.setTarget(this.createEmptyTree());

		// Parse s
		// logger.debug("-------------------- PARSING begin
		// --------------------");
		// logger.debug("s = " + s);
		// logger.debug("in = " + in + " tokens " + in.toTokenArray());
		Match out = parser.completeMatch(in);

		if (out != null)
		{
			// Found complete match
			completeMatch = true;
			target = (T) out.getTarget();
		}
		else
		{
			completeMatch = false;
			logger.error("Unrecognized tree string, running best match");
			out = parser.bestMatch(in);
			logger.debug("in " + in + " out " + out);
			throw new MathParserException(s, "Unrecognized tree string");
		}
		/*
		 * // logger.debug("target expression = " + // target.getExpressionValue());
		 * logger.debug("target expression syntax tree = \n" + target); //
		 * logger.debug("complete Match = "+ // target.isCompleteMatch()); //
		 * logger.debug("target in HTML = \n" + // target.getHTMLString());
		 * logger.debug("########### PARSING end ##############");
		 */
		// logger.debug("-------------------- PARSING end
		// ----------------------");
	}

	/**
	 * Retutrns the target tree constructed by the parser during matching and assembly.
	 * 
	 * @return the target tree
	 */
	public final T getSyntax()
	{
		return target;
	}

	// ========================= GETTERS & SETTERS =========================

	/**
	 * @return the completeMatch
	 */
	public final boolean isCompleteMatch()
	{
		return completeMatch;
	}
}
