//################################################################
// ExtJS Example: a tree widget that mirrors the content
// management item hierarchy.
//################################################################

/**
 * Open an AJAX connection, send the item's ID and populate the
 * content division with an item view HTML (generated by a JSP
 * on the server, which is a forward action of the Struts action we 
 * call here).
 *
 * @param node node whose content is loaded
 * @param node ID parameter to pass into the AJAX action
 * @param options tree UI options struct
 */
function loadContent(node, id, options)
{
	var conn = new Ext.data.Connection();
    	conn.request({
			url: options.url,
			method: 'POST',
			params: { node: id },
	        callback: function(param, success, responseObject) 
			{
	        	// Populate the content div element
	            var content = Ext.get(options.content_element);
	            content.dom.innerHTML = responseObject.responseText;
			}
		});
}
	            
function ItemTreeUI(options)
{
    // shorthand
    var Tree = Ext.tree;
    
    return {
        init : function() {
    		
    		//================= Tree loader =================
    		
    		var treeLoader = new Tree.TreeLoader({dataUrl:'/ru2/content/ajax/explore/tree.do'});
    		
    		// Pass the appropriate request parameters to AJAX node load action
    		treeLoader.on("beforeload", function(loader, node) {
       			loader.baseParams.action_root = ((node.attributes.root == null) ? false : node.attributes.root);
       			loader.baseParams.initId = node.attributes.initId;
    		}, this);

    		//================= Main yui-ext tree ===========

            var tree = new Tree.TreePanel({
                el: options.target_element,
                animate: true, 
                autoScroll: true,
                loader: treeLoader,
                enableDD: false,
                containerScroll: true,
                dropConfig: {}
            });
            
            // add a tree sorter in folder mode
            //new Tree.TreeSorter(tree, {folderSort:true});
            
            // set the root node
            var root = new Tree.AsyncTreeNode({
            	allowDrag: false,
            	allowDrop: false,
                text: 'Root', 
                draggable: false, // disable root node dragging
                id: -1, // Dummy
                initId: options.initId, // id of node to be loaded upon root node construction
                root: true
            });
            tree.setRootNode(root);
            
    		tree.on("click", function(node, e) {
				// Load node content
				loadContent(node, node.attributes.id, options);
    		}, this);
            
    		tree.on("load", function(node) {
    			if (node.attributes.root)
    			{
					// Load node content upon page refresh / tree pre-population
					loadContent(node, node.attributes.initId, options);
    			}
    		}, this);
               
            // render the tree
            tree.render();
            
            root.expand(false, /*no anim*/ false);
        }
    };
}
